import"./assets/modulepreload-polyfill-3cfb730f.js";import{a as f,i as g,P as _}from"./assets/vendor-99c9b1bc.js";document.querySelector(".js-open-menu");document.querySelector(".js-close-menu");document.querySelector(".js-modal");new BroadcastChannel("modal-channel");const j=document.querySelector(".div-theme"),L=document.querySelector(".span-theme"),S=document.querySelector("body");let n=!1;j.addEventListener("change",()=>{n?(n=!1,localStorage.setItem("userTheme","light")):(n=!0,localStorage.setItem("userTheme","dark")),q()});function q(){try{n=localStorage.getItem("userTheme")==="dark"}catch{n=!1}const e=document.querySelector(".header-logo-icon"),t=document.querySelector(".header-logo-icon1");n?(S.classList.add("dark-theme"),L.style.left="20px",e.style.width="0px",t.style.width="109px"):(S.classList.remove("dark-theme"),L.style.left="2px",t.style.width="0px",e.style.width="109px")}q();function u(){const e=document.querySelector("#loader");e?e.classList.add("visible"):console.error("Loader element not found.")}function a(){const e=document.querySelector("#loader");e?e.classList.remove("visible"):console.error("Loader element not found.")}async function C(e){try{u();const t=await f(`https://books-backend.p.goit.global/books/category?category=${e}`);return a(),t.data}catch{a(),g.error({title:"",message:"Failed server request",position:"topRight"})}}async function N(){try{u();const e=await f("https://books-backend.p.goit.global/books/top-books");return a(),e.data}catch{a(),g.error({title:"",message:"Failed server request",position:"topRight"})}}const I=document.querySelector(".nav-categories-list");async function H(){const{data:e}=await f.get("https://books-backend.p.goit.global/books/category-list");return e}const J=async()=>{try{const e=await H();I.innerHTML=await D(e),document.querySelectorAll(".nav-category-item").forEach(o=>{o.addEventListener("click",r=>{const k=document.querySelector(".nav-category-item.active");k&&k.classList.remove("active"),r.target.classList.add("active")})})}catch{console.log("Oops! Something went wrong")}};J();I.addEventListener("click",R);function R(e){e.target.dataset.id&&C(e)}function D(e){return`<li class="nav-category-item active" data-id="all-categories">
        All categories</li>
        ${e.map(t=>`<li class="nav-category-item" data-id="${t.list_name}">
        ${t.list_name}
        </li>`).join("")}`}const p=document.getElementById("bookModal"),W=document.getElementById("bookModalTitle");document.getElementById("bookModalText");const m=document.getElementById("addToShoppingList"),Y=document.querySelector(".modal-close"),w=document.getElementById("modalADText");let l=[],c=[],F={};function b(){p.classList.remove("show"),document.body.style.overflow=""}function G(e){if(!e){console.error("Invalid bookId:",e);return}const t=l.indexOf(e);t===-1?(l.push(e),c.push(F)):(l.splice(t,1),c.splice(t,1)),localStorage.setItem("shoppingList",JSON.stringify(l)),localStorage.setItem("shoppingCard",JSON.stringify(c)),t===-1?(m.innerText="Remove from the shopping list",w.style.display="block"):(m.innerText="Add to shopping list",w.style.display="none")}m.addEventListener("click",()=>{const e=W.dataset.bookId;G(e)});p.addEventListener("click",e=>{e.target===p&&b()});document.addEventListener("keydown",e=>{e.key==="Escape"&&b()});const B=localStorage.getItem("shoppingList"),T=localStorage.getItem("shoppingCard");B&&(l=JSON.parse(B));T&&(c=JSON.parse(T));Y.addEventListener("click",b);const V=document.querySelector(".backdrop"),M=document.querySelector(".js-open-menu");M.insertAdjacentHTML("afterbegin",`<svg class="icon-close visually-hidden" width="28" height="28">
    <use href="../img/sprite.svg#icon-x-close"></use>
  </svg>`);const z=document.querySelector(".icon-close"),Q=document.querySelector(".header-burger-icon");function K(){V.classList.toggle("show__mob-menu"),z.classList.toggle("visually-hidden"),Q.classList.toggle("visually-hidden")}M.addEventListener("click",K);let d=[],s={totalItems:0,itemsPerPage:0,visiblePages:0,template:{page:'<a href="#" class="tui-page-btn">{{page}}</a>',currentPage:'<strong class="tui-page-btn tui-is-selected">{{page}}</strong>',moveButton:'<a href="#" class="tui-page-btn tui-page-btn-moveButton"><span class="tui-ico-{{type}}">{{type}}</span></a>',disabledMoveButton:'<span class="tui-page-btn tui-page-btn-disabledMoveButton tui-is-disabled"><span class="tui-ico-{{type}}">{{type}}</span></span>',moreButton:'<a href="#" class="tui-page-btn tui-page-btn-moreButton tui-{{type}}-is-ellip"><span class="tui-ico-ellip">...</span></a>'}};const x="ShoppingListLocalStorage",E=document.getElementById("pagination-list");function U(e,t){let o=window.localStorage.getItem(x);if(o!==null){let r=JSON.parse(o);s.totalItems=r.length,s.itemsPerPage=e,s.visiblePages=t}}function A(){let e=window.localStorage.getItem(x),t=0;return e==null||JSON.parse(e).length==0?E.style.display="none":(e=JSON.parse(e),t=s.itemsPerPage*v._currentPage-s.itemsPerPage,d=e.slice(t,t+s.itemsPerPage),E.style.display="block"),d}U(3,2);let v=new _("pagination-list",s);v.on("beforeMove",function(e){});v.on("afterMove",function(e){d=A()});d=A();const i=document.querySelector(".main-wrapper");i.addEventListener("click",te);const y=document.querySelector(".scroll-to-top-btn");y.addEventListener("click",X);window.addEventListener("scroll",Z);function X(){window.pageYOffset>0&&window.scrollTo({top:0,behavior:"smooth"})}function Z(){const e=window.pageYOffset,t=document.documentElement.clientHeight;e>t?y.classList.add("scroll-to-top-btn-show"):y.classList.remove("scroll-to-top-btn-show")}async function ee(){P(),u();try{const e=await N();le(e)}catch{g.error({title:"",message:"Whoops! Somethink went wrong",position:"topRight"})}finally{a()}}ee();async function te(e){if(!e.target.classList.contains("see-more-btn"))return;P(),u();const t=e.target.dataset.category;try{const o=await C(t);ce(o)}catch{g.error({title:"",message:"Sorry, we couldn't find any books in this category",position:"topRight"})}finally{a()}}function O(e,t){return`<li class="${t}" data-id="${e._id}">
                 <div class="overlay-box">
                   <img
                     class="book-img"
                     src="${e.book_image}"
                     alt="${e.title}"
                     width="180"
                     height="256"
                   />
                   <p class="overlay-text">Quick View</p>
                 </div>
                 <div class="book-info">
                   <h3 class="book-title">${e.title}</h3>
                   <p class="book-author">${e.author}</p>
                 </div>
               </li>`}function oe(e){const t=e.books.map(o=>O(o,"best-sellers-list-item")).join("");return`<div class="best-sellers-container">
             <h2 class="category-title">${e.list_name}</h2>
             <ul class="best-sellers-list">${t}</ul>
             <div class="see-more-btn-wrapper">
               <button class="see-more-btn" type="button" data-category="${e.list_name}">See more</button>
             </div>
           </div>`}function se(e){return`<ul class="category-list">${e.map(o=>O(o,"category-list-item")).join("")}</ul>`}function ne(e){i.insertAdjacentHTML("beforeend",oe(e))}function ae(e){i.insertAdjacentHTML("beforeend",se(e))}function ie(){i.insertAdjacentHTML("afterbegin",`<h1 class="main-title">
            Best Sellers <span class="accent-text">Books</span>
        </h1>`)}function re(e){const t=e[0].list_name.split(" "),o=t.pop(),r=`${t.join(" ")} <span class="accent-text">${o}</span>`;i.insertAdjacentHTML("afterbegin",`<h1 class="main-title">${r}</h1>`)}function P(){i.innerHTML=""}function le(e){e.forEach(ne),ie()}function ce(e){ae(e),re(e)}const h=document.querySelector(".back-top");window.addEventListener("scroll",de);h.addEventListener("click",$);function de(){const e=window.pageYOffset,t=document.documentElement.clientHeight;e>t?h.classList.add("back-top-show"):h.classList.remove("back-top-show")}function $(){window.pageYOffset>0&&(window.scrollBy(0,-25),setTimeout($,0))}
//# sourceMappingURL=commonHelpers.js.map
