import"./assets/modulepreload-polyfill-3cfb730f.js";import{a as y,i as l}from"./assets/vendor-94296d0c.js";document.querySelector(".js-open-menu");document.querySelector(".js-close-menu");document.querySelector(".js-modal");new BroadcastChannel("modal-channel");const I=document.querySelector(".div-theme"),k=document.querySelector(".span-theme"),b=document.querySelector("body");let s=!1;I.addEventListener("change",()=>{s?(s=!1,localStorage.setItem("userTheme","light")):(s=!0,localStorage.setItem("userTheme","dark")),w()});function w(){try{s=localStorage.getItem("userTheme")==="dark"}catch{s=!1}const e=document.querySelector(".header-logo-icon"),t=document.querySelector(".header-logo-icon1");s?(b.classList.add("dark-theme"),k.style.left="20px",e.style.width="0px",t.style.width="109px"):(b.classList.remove("dark-theme"),k.style.left="2px",t.style.width="0px",e.style.width="109px")}w();function d(){const e=document.querySelector("#loader");e?e.classList.add("visible"):console.error("Loader element not found.")}function n(){const e=document.querySelector("#loader");e?e.classList.remove("visible"):console.error("Loader element not found.")}async function T(e){try{d();const t=await y(`https://books-backend.p.goit.global/books/category?category=${e}`);return n(),t.data}catch{n(),l.error({title:"",message:"Failed server request",position:"topRight"})}}async function M(){try{d();const e=await y("https://books-backend.p.goit.global/books/top-books");return n(),e.data}catch{n(),l.error({title:"",message:"Failed server request",position:"topRight"})}}const B=document.querySelector(".nav-categories-list");async function $(){const{data:e}=await y.get("https://books-backend.p.goit.global/books/category-list");return e}const O=async()=>{try{const e=await $();B.innerHTML=await _(e),document.querySelectorAll(".nav-category-item").forEach(o=>{o.addEventListener("click",r=>{const f=document.querySelector(".nav-category-item.active");f&&f.classList.remove("active"),r.target.classList.add("active")})})}catch{console.log("Oops! Something went wrong")}};O();B.addEventListener("click",j);function j(e){e.target.dataset.id&&T(e)}function _(e){return`<li class="nav-category-item active" data-id="all-categories">
        All categories</li>
        ${e.map(t=>`<li class="nav-category-item" data-id="${t.list_name}">
        ${t.list_name}
        </li>`).join("")}`}const g=document.getElementById("bookModal"),H=document.getElementById("bookModalTitle");document.getElementById("bookModalText");const u=document.getElementById("addToShoppingList"),N=document.querySelector(".modal-close"),L=document.getElementById("modalADText");let i=[],c=[],J={};function h(){g.classList.remove("show"),document.body.style.overflow=""}function R(e){if(!e){console.error("Invalid bookId:",e);return}const t=i.indexOf(e);t===-1?(i.push(e),c.push(J)):(i.splice(t,1),c.splice(t,1)),localStorage.setItem("shoppingList",JSON.stringify(i)),localStorage.setItem("shoppingCard",JSON.stringify(c)),t===-1?(u.innerText="Remove from the shopping list",L.style.display="block"):(u.innerText="Add to shopping list",L.style.display="none")}u.addEventListener("click",()=>{const e=H.dataset.bookId;R(e)});g.addEventListener("click",e=>{e.target===g&&h()});document.addEventListener("keydown",e=>{e.key==="Escape"&&h()});const v=localStorage.getItem("shoppingList"),S=localStorage.getItem("shoppingCard");v&&(i=JSON.parse(v));S&&(c=JSON.parse(S));N.addEventListener("click",h);const P=document.querySelector(".backdrop"),E=document.querySelector(".js-open-menu");E.insertAdjacentHTML("afterbegin",`<svg class="icon-close visually-hidden" width="28" height="28">
    <use href="../img/sprite.svg#icon-x-close"></use>
  </svg>`);const W=document.querySelector(".icon-close"),Y=document.querySelector(".header-burger-icon");function D(){P.classList.toggle("show__mob-menu"),W.classList.toggle("visually-hidden"),Y.classList.toggle("visually-hidden")}E.addEventListener("click",D);const q="ShoppingListLocalStorage";document.getElementById("pagination-list");function F(e,t){let o=window.localStorage.getItem(q);o!==null&&JSON.parse(o).length}function z(){let e=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22];localStorage.setItem(q,JSON.stringify(e))}z();F();const a=document.querySelector(".main-wrapper");a.addEventListener("click",K);const m=document.querySelector(".scroll-to-top-btn");m.addEventListener("click",G);window.addEventListener("scroll",Q);function G(){window.pageYOffset>0&&window.scrollTo({top:0,behavior:"smooth"})}function Q(){const e=window.pageYOffset,t=document.documentElement.clientHeight;e>t?m.classList.add("scroll-to-top-btn-show"):m.classList.remove("scroll-to-top-btn-show")}async function V(){x(),d();try{const e=await M();se(e)}catch{l.error({title:"",message:"Whoops! Somethink went wrong",position:"topRight"})}finally{n()}}V();async function K(e){if(!e.target.classList.contains("see-more-btn"))return;x(),d();const t=e.target.dataset.category;try{const o=await T(t);ne(o)}catch{l.error({title:"",message:"Sorry, we couldn't find any books in this category",position:"topRight"})}finally{n()}}function C(e,t){return`<li class="${t}" data-id="${e._id}">
                 <div class="overlay-box">
                   <img
                     class="book-img"
                     src="${e.book_image}"
                     alt="${e.title}"
                     width="180"
                     height="256"
                   />
                   <p class="overlay-text">Quick View</p>
                 </div>
                 <div class="book-info">
                   <h3 class="book-title">${e.title}</h3>
                   <p class="book-author">${e.author}</p>
                 </div>
               </li>`}function U(e){const t=e.books.map(o=>C(o,"best-sellers-list-item")).join("");return`<div class="best-sellers-container">
             <h2 class="category-title">${e.list_name}</h2>
             <ul class="best-sellers-list">${t}</ul>
             <div class="see-more-btn-wrapper">
               <button class="see-more-btn" type="button" data-category="${e.list_name}">See more</button>
             </div>
           </div>`}function X(e){return`<ul class="category-list">${e.map(o=>C(o,"category-list-item")).join("")}</ul>`}function Z(e){a.insertAdjacentHTML("beforeend",U(e))}function ee(e){a.insertAdjacentHTML("beforeend",X(e))}function te(){a.insertAdjacentHTML("afterbegin",`<h1 class="main-title">
            Best Sellers <span class="accent-text">Books</span>
        </h1>`)}function oe(e){const t=e[0].list_name.split(" "),o=t.pop(),r=`${t.join(" ")} <span class="accent-text">${o}</span>`;a.insertAdjacentHTML("afterbegin",`<h1 class="main-title">${r}</h1>`)}function x(){a.innerHTML=""}function se(e){e.forEach(Z),te()}function ne(e){ee(e),oe(e)}const p=document.querySelector(".back-top");window.addEventListener("scroll",ae);p.addEventListener("click",A);function ae(){const e=window.pageYOffset,t=document.documentElement.clientHeight;e>t?p.classList.add("back-top-show"):p.classList.remove("back-top-show")}function A(){window.pageYOffset>0&&(window.scrollBy(0,-25),setTimeout(A,0))}
//# sourceMappingURL=commonHelpers.js.map
